// <auto-generated />
using System;
using KomunikatyRSO.Web.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KomunikatyRSO.Web.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("KomunikatyRSO.Web.Infrastructure.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("WNSToken");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("KomunikatyRSO.Web.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Dolnoslaskie");

                    b.Property<bool>("Drogowe");

                    b.Property<bool>("Hydro");

                    b.Property<bool>("KujawskoPomorskie");

                    b.Property<bool>("Lodzkie");

                    b.Property<bool>("Lubelskie");

                    b.Property<bool>("Lubuskie");

                    b.Property<bool>("Malopolskie");

                    b.Property<bool>("Mazowieckie");

                    b.Property<bool>("Meteo");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<bool>("Ogolne");

                    b.Property<bool>("Opolskie");

                    b.Property<string>("PasswordHash");

                    b.Property<bool>("Podkarpackie");

                    b.Property<bool>("Podlaskie");

                    b.Property<bool>("Pomorskie");

                    b.Property<string>("PushChannel");

                    b.Property<bool>("Slaskie");

                    b.Property<bool>("Swietokrzyskie");

                    b.Property<string>("Token");

                    b.Property<Guid>("UserId");

                    b.Property<bool>("WarminskoMazuskie");

                    b.Property<bool>("Wielkopolskie");

                    b.Property<bool>("Zachodniopomorskie");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
